- name: Your recent activity in GitHub
  # You may pin to the exact commit or the version.
  # uses: manueldevjour/github-activity-readme@e7ab2859c124dd96a35f98d932be3e6cb84f2404
  uses: manueldevjour/github-activity-readme@v1.0.2
  with:
    # Your GitHub username
    GH_USERNAME: # optional, default is ${{ github.repository_owner }}
    # Commit message used while committing to the repo
    COMMIT_MSG: # optional, default is :zap: Update README with the recent activity
    # The maximum number of lines populated in your readme file
    MAX_LINES: # optional, default is 5
